kind: pipeline
name: Build_1

steps:
  - name: test_1
    image: perl
    environment:
      COVERALLS_REPO_TOKEN:
        from_secret: COVERALLS_REPO_TOKEN
      COVERALLS_FLAG_NAME: test00
      COVERALLS_PARALLEL: true
    commands:
      - cpanm --quiet --installdeps --notest .
      - perl Build.PL build && ./Build
      - PERL5LIB=blib/lib cover -test -silent -select ^t/00 -report coveralls
---
kind: pipeline
name: Build_2

steps:
  - name: test_2
    image: perl
    environment:
      COVERALLS_REPO_TOKEN:
        from_secret: COVERALLS_REPO_TOKEN
      COVERALLS_FLAG_NAME: test01
      COVERALLS_PARALLEL: true
    commands:
      - cpanm --quiet --installdeps --notest .
      - perl Build.PL build && ./Build
      - PERL5LIB=blib/lib cover -test -silent -select ^t/01 -report coveralls
---

kind: pipeline
name: Coveralls_webhook_done

steps:
  - name: send_done
    image: plugins/webhook
    settings:
      urls:
        from_secret: COVERALLS_WEBHOOK_URL
      content_type: application/json
      debug: true
      template: |
        {
          "payload": {
            "build_num": ${DRONE_BUILD_NUMBER},
            "status": "done"
          }
        }
depends_on:
  - Build_1
  - Build_2
